version: '3.8'

services:
  
  db:
    image: postgres:13.3
    volumes:
      - .data/db:/var/lib/postgresql/data
    env_file: '.env'
    ports:
      - '5432:5432'
    expose:
      - 5432

  web:
    build:
      context: .
    command: >
      sh -c 'python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8080'
    ports:
      - '8080:8080'
    expose:
      - 8080  
    volumes:
      - '.:/usr/src/app'
    env_file: '.env'
    
    depends_on:
      - db