# Generated by Django 5.0 on 2023-12-29 20:11

import django.db.models.deletion
import lib.utils.model_functions
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ORDER', 'Order'), ('INVOICE', 'Invoice')], default='ORDER', max_length=30, unique=True)),
                ('document_number', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=lib.utils.model_functions.custom_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('order_time', models.DateTimeField(auto_now=True)),
                ('order_number', models.IntegerField(editable=False, unique=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
            ],
            options={
                'ordering': ('-order_number',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.CharField(default=lib.utils.model_functions.custom_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=95, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineItem',
            fields=[
                ('id', models.CharField(default=lib.utils.model_functions.custom_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=128)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_without_tax', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('tax_name', models.CharField(max_length=32)),
                ('tax_amount', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='home.purchaseorder')),
            ],
            options={
                'ordering': ('purchase_order',),
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='related_orders', to='home.supplier'),
        ),
    ]
