# Generated by Django 5.0 on 2023-12-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_documentcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentcounter',
            name='document_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('INVOICE', 'Invoice')], default='ORDER', max_length=30, unique=True),
        ),
    ]
