# Generated by Django 5.0 on 2023-12-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_purchaseorder_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitem',
            name='line_total',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='price_without_tax',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
