# Generated by Django 5.0 on 2023-12-29 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_lineitem_line_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'ordering': ('purchase_order',)},
        ),
    ]
